---
name: Build and Test apxproof

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: apt-get install -y poppler-utils imagemagick pdftk qpdf
      - run: make clean && make && make test
